theme: jekyll-theme-slate
title: Welcome to Shaun Richardson's homepage!
description: This page is for my SNHU CS499-T5477 Capstone course. Feel free to bookmark this to keep an eye on my project updates and thank you for stopping by
